### ISSUE TITLE
flit not finding `__summary__` imported from an `__about__.py`

### ISSUE THREAD

**Issue by NickleDave** [pypa/flit#494]
Hi @takluyver I am switching to `flit` but am running into an issue when I test my re-written `pyproject.toml` by running `flit install`.

It seems like `flit` is not finding the `__summary__` that I import in `__init__.py` from a separate `__about__.py` file?

I could just change code to declare it directly in `__init__.py` but I thought it might be worth raising an issue since this approach of declaring in a separate module and importing is one of the ones recommended on the PyPA guide (number 3 on this page):
https://packaging.python.org/en/latest/guides/single-sourcing-package-version/

Very possible that I am just not doing something right though.  
Here's the full traceback I get:
```
ERROR: Command errored out with exit status 1:
   command: /home/pimienta/Documents/repos/coding/vocal/evfuncs/.venv/bin/python3 /home/pimienta/Documents/repos/coding/vocal/evfuncs/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpkw297g4f
       cwd: /home/pimienta/Documents/repos/coding/vocal/evfuncs
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/home/pimienta/Documents/repos/coding/vocal/evfuncs/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/pimienta/Documents/repos/coding/vocal/evfuncs/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/pimienta/Documents/repos/coding/vocal/evfuncs/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/tmp/pip-build-env-z2kioxie/overlay/lib/python3.8/site-packages/flit_core/buildapi.py", line 49, in prepare_metadata_for_build_wheel
      metadata = make_metadata(module, ini_info)
    File "/tmp/pip-build-env-z2kioxie/overlay/lib/python3.8/site-packages/flit_core/common.py", line 396, in make_metadata
      md_dict.update(get_info_from_module(module, ini_info.dynamic_metadata))
    File "/tmp/pip-build-env-z2kioxie/overlay/lib/python3.8/site-packages/flit_core/common.py", line 199, in get_info_from_module
      raise NoDocstringError(
  flit_core.common.NoDocstringError: Flit cannot package module without docstring, or empty docstring. Please add a docstring to your module (/home/pimienta/Documents/repos/coding/vocal/evfuncs/src/evfuncs/__init__.py).
  ----------------------------------------
WARNING: Discarding file:///home/pimienta/Documents/repos/coding/vocal/evfuncs. Command errored out with exit status 1: /home/pimienta/Documents/repos/coding/vocal/evfuncs/.venv/bin/python3 /home/pimienta/Documents/repos/coding/vocal/evfuncs/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpkw297g4f Check the logs for full command output.
ERROR: Command errored out with exit status 1: /home/pimienta/Documents/repos/coding/vocal/evfuncs/.venv/bin/python3 /home/pimienta/Documents/repos/coding/vocal/evfuncs/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpkw297g4f Check the logs for full command output.
Traceback (most recent call last):
  File "/home/pimienta/Documents/repos/coding/vocal/evfuncs/.venv/bin/flit", line 10, in <module>
    sys.exit(main())
  File "/home/pimienta/Documents/repos/coding/vocal/evfuncs/.venv/lib/python3.8/site-packages/flit/__init__.py", line 193, in main
    Installer.from_ini_path(args.ini_file, user=args.user, python=python,
  File "/home/pimienta/Documents/repos/coding/vocal/evfuncs/.venv/lib/python3.8/site-packages/flit/install.py", line 419, in install
    self.install_with_pip()
  File "/home/pimienta/Documents/repos/coding/vocal/evfuncs/.venv/lib/python3.8/site-packages/flit/install.py", line 357, in install_with_pip
    check_call(cmd, shell=shell)
  File "/home/pimienta/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/pimienta/Documents/repos/coding/vocal/evfuncs/.venv/bin/python3', '-m', 'pip', 'install', '.[test]']' returned non-zero exit status 1.
```

Branch in progress with re-written `pyproject.toml` is here in case it helps:  
https://github.com/NickleDave/evfuncs/tree/switch-flit

**Comment by takluyver** [comment]
It doesn't actually look for `__summary__` at all - it looks for a docstring in the `__init__.py` file. Though if you prefer, you can also specify `description` in pyproject.toml directly.

**Comment by NickleDave** [comment]
Ah, sorry I was unclear.

This is what the top of my `__init__.py` looks like:

```
from .__about__ import (
    __author__,
    __commit__,
    __copyright__,
    __email__,
    __license__,
    __summary__,
    __title__,
    __uri__,
    __version__,
)
```

which is what `warehouse` does, as linked to by the pypa guide:
https://github.com/pypa/warehouse/blob/64ca42e42d5613c8339b3ec5e1cb7765c6b23083/warehouse/__init__.py

**Comment by takluyver** [comment]
That will work for the version number but, as things stand, not for the description. Note that Warehouse isn't packaged with Flit, and that guide you linked to doesn't refer to Flit at all. :wink:  I think setting `__doc__ == __summary__` would probably work around it if you wanted, though.

We could add looking at `__summary__`, but I'd rather not make this mechanism more complicated. The one line summary generally doesn't change very often, so it doesn't seem worth putting much effort into reading it dynamically. To be honest, if I was designing a new tool like Flit, I probably wouldn't bother making it dynamic at all.

**Comment by NickleDave** [comment]
I see.  

Very understood, thank you for not making `flit` more dynamic than it needs to be 😏 .
Agreed that the summary isn't likely to change.
I can just use that workaround or copy it.

I will go ahead and close this. Thank you @takluyver
