### ISSUE TITLE
optional-dependencies do not work in pip 22

### ISSUE THREAD

**Issue by codingjoe** [pypa/flit#554]
I get the following error, when installing extra dependencies with pip v22. When I downgrade to pip v21, everything works as expected.

```bash
$ pip install --version
> pip 22.1
$ pip install -e .[test]
```

```python
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 340, in run
    requirement_set = resolver.resolve(
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 75, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 506, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 468, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 188, in _make_candidate_from_link
    self._editable_candidate_cache[link] = EditableCandidate(
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 316, in __init__
    super().__init__(
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 161, in __init__
    self.dist = self._prepare()
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 230, in _prepare
    dist = self._prepare_distribution()
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 326, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 543, in prepare_editable_requirement
    dist = _get_prepared_distribution(
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 57, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 45, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 114, in _install_build_reqs
    conflicting, missing = self.req.build_env.check_requirements(build_reqs)
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_internal/build_env.py", line 178, in check_requirements
    if req.marker is not None and not req.marker.evaluate():
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_vendor/packaging/markers.py", line 304, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_vendor/packaging/markers.py", line 234, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/Users/johannes/GitHub/codingjoe/django-pictures/venv/lib/python3.10/site-packages/pip/_vendor/packaging/markers.py", line 215, in _get_env
    raise UndefinedEnvironmentName(
pip._vendor.packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.
```

**Comment by codingjoe** [comment]
Don't know who's "fault" this is. Therefore I opened another issue here https://github.com/pypa/pip/issues/11133

**Comment by takluyver** [comment]
Looks like there's a fix coming from pip, but reading through the issues on pip, it looks like it might make sense for Flit to also not include optional dependencies in the list of build dependencies.

**Comment by codingjoe** [comment]
Thanks @takluyver, pip 22.1.1 will fix this. I will close the issue, since there's no todo here.
