### ISSUE TITLE
Dynamic description is not working with pip 22.2

### ISSUE THREAD

**Issue by furiosamg** [pypa/flit#575]
Minimal reproduction: https://github.com/furiosamg/flit-dynamic-pip-22

I think flit's dynamic description generation is broken in pip 22.2.
When trying to install above package with pip 22.2, following error occurred.

```text
$ pip install pip==22.2 && pip install .
Looking in indexes: https://pypi.org/simple, https://internal-pypi.furiosa.dev/simple
Requirement already satisfied: pip==22.2 in /root/miniconda3/envs/env-3.9/lib/python3.9/site-packages (22.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Looking in indexes: https://pypi.org/simple, https://internal-pypi.furiosa.dev/simple
Processing /root/flit-dynamic-pip-22
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 2
  ╰─> [45 lines of output]
      Looking in indexes: https://pypi.org/simple, https://internal-pypi.furiosa.dev/simple, https://internal-pypi.furiosa.dev/simple
      Collecting flit_core<4,>=3.2
        Using cached flit_core-3.7.1-py3-none-any.whl (60 kB)
      Installing collected packages: flit_core
      /root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:103: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
        warnings.warn(msg, _ExperimentalProjectMetadata)
      ERROR: Exception:
      Traceback (most recent call last):
        File "/root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
          status = run_func(*args)
        File "/root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
          return func(self, options, args)
        File "/root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 461, in run
          installed = install_given_reqs(
        File "/root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/pip/_internal/req/__init__.py", line 73, in install_given_reqs
          requirement.install(
        File "/root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 752, in install
          scheme = get_scheme(
        File "/root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/pip/_internal/locations/__init__.py", line 246, in get_scheme
          old = _distutils.get_scheme(
        File "/root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/pip/_internal/locations/_distutils.py", line 130, in get_scheme
          scheme = distutils_scheme(dist_name, user, home, root, isolated, prefix)
        File "/root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/pip/_internal/locations/_distutils.py", line 46, in distutils_scheme
          d.parse_config_files()
        File "/root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/setuptools/dist.py", line 854, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 55, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "/root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 135, in read_configuration
          return expand_configuration(asdict, root_dir, ignore_option_errors, dist)
        File "/root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 190, in expand_configuration
          return _ConfigExpander(config, root_dir, ignore_option_errors, dist).expand()
        File "/root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 237, in expand
          self._expand_all_dynamic(dist, package_dir)
        File "/root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 272, in _expand_all_dynamic
          obtained_dynamic = {
        File "/root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 273, in <dictcomp>
          field: self._obtain(dist, field, package_dir)
        File "/root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 310, in _obtain
          self._ensure_previously_set(dist, field)
        File "/root/miniconda3/envs/env-3.9/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 296, in _ensure_previously_set
          raise OptionError(msg)
      distutils.errors.DistutilsOptionError: No configuration found for dynamic 'description'.
      Some dynamic fields need to be specified via `tool.setuptools.dynamic`
      others must be specified via the equivalent attribute in `setup.py`.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 2
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip
```

**Comment by takluyver** [comment]
Your package builds and installs fine for me (see below). :confused: 

It looks like pip is using some distutils/setuptools code to work out destination paths, and setuptools ends up trying to parse the metadata from `pyproject.toml` assuming that it's built with setuptools. What version of setuptools do you have? I've just tried updating to the latest and I still don't see the issue.

Do you have any [pip config](https://pip.pypa.io/en/stable/topics/configuration/) in files or environment variables?

```
$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/takluyver/Code/flit-dynamic-pip-22
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: flitdynamicpip22
  Building wheel for flitdynamicpip22 (pyproject.toml) ... done
  Created wheel for flitdynamicpip22: filename=flitdynamicpip22-0.0.1-py2.py3-none-any.whl size=1101 sha256=0a1efe3e78bd38c63c5ce540cc616d72da889be62233e2e61033f5b67ade985e
  Stored in directory: /home/takluyver/.cache/pip/wheels/df/08/86/74c3e5aa6010da77b6ecae2b31a34efd35815ddc26e6b382b3
Successfully built flitdynamicpip22
Installing collected packages: flitdynamicpip22
Successfully installed flitdynamicpip22-0.0.1

$ pip --version
pip 22.2 from /home/takluyver/.local/lib/python3.10/site-packages/pip (python 3.10)
```

**Comment by furiosamg** [comment]
Thanks for the comment.

When I try to install my package with Python 3.10, the installation succeeds. 🤔 But not with 3.8, 3.9.
Could you please try with Python 3.8 or 3.9?

P.S. I think I haven't set any pip configuration.

**Comment by takluyver** [comment]
Thanks, when I make a Python 3.9 environment, I do see the same error.

I still don't think this is a Flit bug - I think the issue is somewhere between pip & setuptools, because it looks like setuptools is trying to get the package metadata as if it was a setuptools package, which is wrong. But I don't know when I'll have time to dig into it to work out exactly what is going wrong.

Other than digging through the traceback to figure out what is going on, you could try using git bisect to identify which change in pip introduced or revealed the problem.

**Comment by furiosamg** [comment]
I agree with that flit is innocent 😇 
The reason I raised the issue here was because I thought dynamic description generation was a flit's functionality.

Thanks for gentle and quick response.

**Comment by pradyunsg** [comment]
Pinging @abravalheri since setuptools' pyproject.toml support seems to be implicated in this.

**Comment by abravalheri** [comment]
> The only reason that I can think of is if setuptools' distutils hack has some logic to detect pip that's broken in 22.2.

I can confirm that the [custom import logic](https://github.com/pypa/setuptools/blob/417018d3299bb33e87d2fccec48790cf3e9dd797/_distutils_hack/__init__.py#L140-L167) don't seem to be working for pip 22.2: in `pip/_internal/locations/_distutils.py`, `distutils` is loaded from `setuptools/_distutils`, which is related to pypa/pip#8761.

Maybe we can avoid this error if [`PipImportRedirectingFinder`](https://github.com/pypa/pip/blob/main/src/pip/__pip-runner__.py) is added *after* [`DistutilsMetaFinder`](https://github.com/pypa/setuptools/blob/main/_distutils_hack/__init__.py)?

Something like:

```diff
- sys.meta_path.insert(0, PipImportRedirectingFinder())
+ def _install():
+    for i, finder in enumerate(sys.meta_path):
+        if "DistutilsMetaFinder" in str(type(finder)):
+            sys.meta_path.insert(i + 1, PipImportRedirectingFinder())
+            return
+
+    sys.meta_path.insert(0, PipImportRedirectingFinder())
+
+
+ _install()
```

**Comment by pradyunsg** [comment]
Ah, well, that's interesting and would fix the immediate bleeding. I think it's reasonable for us to do a `sys.meta_path.append(...)` instead of the `sys.meta_path.insert(0, ...)`.

We actually changed this to the start on the rationale that no one else should try modifying pip before us (https://github.com/pypa/pip/pull/11257#discussion_r921138585) but setuptools use case seems like a reasonable one.

**Comment by furiosamg** [comment]
Thank you all for your support and interest. I'd be happy to wait.

**Comment by abravalheri** [comment]
Thank you very much for the feedback @pradyunsg.

There might be other ways of handling this in the setuptools side, but I think that this is the most straight forward... Without the custom finder intercepting `pip`, we would need some kind of signalling from `pip` to avoid replacing `distutils` (e.g. [the approach described by Jason](https://github.com/pypa/pip/issues/8761#issuecomment-1036408539)).

@furiosamg, meanwhile you can try exporting `SETUPTOOLS_USE_DISTUTILS=stdlib` as an environment variable.

**Comment by furiosamg** [comment]
@abravalheri Thanks, I checked that workaround works. Great!

**Comment by pradyunsg** [comment]
I'll move this over to pip, since we need to make a change on pip's end.
