### ISSUE TITLE
OSError: [WinError 1314] A required privilege is not held by the client

### ISSUE THREAD

**Issue by dinhanhx** [pypa/flit#599]
Environment on Windows
```
virtualenv 20.2.2
python 3.8
certifi            2022.9.24
charset-normalizer 2.1.1
docutils           0.19
flit               3.7.1
flit_core          3.7.1
idna               3.4
pip                22.2.2
requests           2.28.1
setuptools         65.3.0
tomli              2.0.1
tomli_w            1.0.0
urllib3            1.26.12
wheel              0.37.1
```

Create a project like normal, run `flit init`, then `flit install --symlink`

full error logs

```
(test-flit) C:\Users\DinhAnh\Desktop\test-flit>flit install --symlink
Extras to install for deps 'all': {'.none'}             I-flit.install
Symlinking dummy -> C:\Users\DinhAnh\Envs\test-flit\Lib\site-packages\dummy  I-flit.install
Traceback (most recent call last):
  File "f:\installed automatically program\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "f:\installed automatically program\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\DinhAnh\Envs\test-flit\Scripts\flit.exe\__main__.py", line 7, in <module>
  File "C:\Users\DinhAnh\Envs\test-flit\lib\site-packages\flit\__init__.py", line 192, in main
    Installer.from_ini_path(args.ini_file, user=args.user, python=python,
  File "C:\Users\DinhAnh\Envs\test-flit\lib\site-packages\flit\install.py", line 430, in install
    self.install_directly()
  File "C:\Users\DinhAnh\Envs\test-flit\lib\site-packages\flit\install.py", line 324, in install_directly
    os.symlink(src.resolve(), dst)
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\DinhAnh\\Desktop\\test-flit\\dummy' -> 'C:\\Users\\DinhAnh\\Envs\\test-flit\\Lib\\site-packages\\dummy'
```

I'm not sure which permission I need.

Alternative solution: `pip install -e .`

**Comment by dinhanhx** [comment]
This issue maybe related to #584

**Comment by dinhanhx** [comment]
I think we can [create symlink through Junction option on Windows](https://stackoverflow.com/a/71759618/13358358).

**Comment by takluyver** [comment]
You can use the `--pth-file` option on Windows instead, or use `pip install -e .` (which works like `--pth-file`). I don't think Windows 'junctions' are precisely the same as symlinks, and I'm not really interested in figuring out more about them. Windows seems to be gradually making symlink support better, so maybe in a few years more it will just work.
